/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include "coptions.h"

void  COptions::initDialog(){
  this->resize(350,280);
  this->setMinimumSize(0,0);
  QGroupBox_1= new QGroupBox(this);
  QGroupBox_1->setGeometry(110,10,230,160);
  QGroupBox_1->setMinimumSize(0,0);
  QGroupBox_1->setTitle("Background");

  QLabel_1= new QLabel(this);
  QLabel_1->setGeometry(10,10,70,20);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText("Free cell:");

  QPushButton_OK= new QPushButton(this);
  QPushButton_OK->setGeometry(10,240,70,23);
  QPushButton_OK->setMinimumSize(0,0);
  QPushButton_OK->setText("OK");

  QScrollBar_EMPTY= new QScrollBar(this);
  QScrollBar_EMPTY->setGeometry(10,130,74,16);
  QScrollBar_EMPTY->setMinimumSize(0,0);
  QScrollBar_EMPTY->setRange(0,1);
  //QScrollBar_EMPTY->setOrientation(QScrollBar::Horizontal);

  QPushButton_CANCEL= new QPushButton(this);
  QPushButton_CANCEL->setGeometry(270,240,70,23);
  QPushButton_CANCEL->setMinimumSize(0,0);
  QPushButton_CANCEL->setText("Cancel");

  QRadioButton_FILE= new QRadioButton(this);
  QRadioButton_FILE->setGeometry(130,30,100,20);
  QRadioButton_FILE->setMinimumSize(0,0);
  QRadioButton_FILE->setText("File");

  QLineEdit_BACKGROUND= new QLineEdit(this);
  QLineEdit_BACKGROUND->setGeometry(130,50,190,20);
  QLineEdit_BACKGROUND->setMinimumSize(0,0);
  QLineEdit_BACKGROUND->setText("");

  QRadioButton_COLOR= new QRadioButton(this);
  QRadioButton_COLOR->setGeometry(130,100,100,20);
  QRadioButton_COLOR->setMinimumSize(0,0);
  QRadioButton_COLOR->setText("Color");

  QPushButton_SELECTFILE= new QPushButton(this);
  QPushButton_SELECTFILE->setGeometry(250,80,70,23);
  QPushButton_SELECTFILE->setMinimumSize(0,0);
  QPushButton_SELECTFILE->setText("Select");

  QWidget_COLORWIDGET= new QWidget(this);
  QWidget_COLORWIDGET->setGeometry(130,130,30,30);
  QWidget_COLORWIDGET->setMinimumSize(0,0);
  QWidget_COLORWIDGET->setFocus();
  QLabel_2= new QLabel(this);
  QLabel_2->setGeometry(10,190,140,23);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setText("Number of free cells:");

  QSpinBox_NUMFREECELLS= new QSpinBox(this);
  QSpinBox_NUMFREECELLS->setGeometry(150,190,50,23);
  QSpinBox_NUMFREECELLS->setMinimumSize(0,0);
  QSpinBox_NUMFREECELLS->setRange(0,4);
  QSpinBox_NUMFREECELLS->setValue(4);

}
